### ISSUE TITLE
post에서 image 예외처리

### ISSUE THREAD

**Issue by sundoforce** [siner308/blog#38]
---
date: 2021-05-28
image: https://user-images.githubusercontent.com/34048253/138473541-ca9eef72-8d1f-4a24-8115-fe96b01f1eb0.png
---

markdown 문서에 image 가 없으면 에러 나는 것 같아서 
혹시 확인 부탁드립니다.
꾸벅

**Comment by siner308** [comment]
sample markdown 추가하여 graphql schema가 생성되도록 해두었습니다.

앞으로 추가되는 Metadata에 대해서도 해당 파일을 통해 확인이 가능할 예정입니다
